### ISSUE TITLE
Error when publishing a release to github

### ISSUE THREAD

**Issue by fergiemcdowall** [conventional-changelog/conventional-github-releaser#46] opened 2017-07-05 06:02 UTC
For some reason I started getting this error when publishing to GitHub, although it _seems_ as though the actual release works fine:

```
> search-index-adder@0.3.6 github-release /Users/fergusmcdowall/node/search-index-adder
> conventional-github-releaser -p angular

[ { url: 'https://api.github.com/repos/fergiemcdowall/search-index-adder/releases/6932093',
    assets_url: 'https://api.github.com/repos/fergiemcdowall/search-index-adder/releases/6932093/assets',
    upload_url: 'https://uploads.github.com/repos/fergiemcdowall/search-index-adder/releases/6932093/assets{?name,label}',
    html_url: 'https://github.com/fergiemcdowall/search-index-adder/releases/tag/v0.3.6',
    id: 6932093,
    tag_name: 'v0.3.6',
    target_commitish: 'master',
    name: 'v0.3.6',
    draft: false,
    author:
     { login: 'fergiemcdowall',
       id: 1122333,
       avatar_url: 'https://avatars2.githubusercontent.com/u/1122333?v=3',
       gravatar_id: '',
       url: 'https://api.github.com/users/fergiemcdowall',
       html_url: 'https://github.com/fergiemcdowall',
       followers_url: 'https://api.github.com/users/fergiemcdowall/followers',
       following_url: 'https://api.github.com/users/fergiemcdowall/following{/other_user}',
       gists_url: 'https://api.github.com/users/fergiemcdowall/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/fergiemcdowall/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/fergiemcdowall/subscriptions',
       organizations_url: 'https://api.github.com/users/fergiemcdowall/orgs',
       repos_url: 'https://api.github.com/users/fergiemcdowall/repos',
       events_url: 'https://api.github.com/users/fergiemcdowall/events{/privacy}',
       received_events_url: 'https://api.github.com/users/fergiemcdowall/received_events',
       type: 'User',
       site_admin: false },
    prerelease: false,
    created_at: '2017-07-03T05:13:19Z',
    published_at: '2017-07-05T05:56:41Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/fergiemcdowall/search-index-adder/tarball/v0.3.6',
    zipball_url: 'https://api.github.com/repos/fergiemcdowall/search-index-adder/zipball/v0.3.6',
    body: '### Features\n\n* **indexing:** can now do appendOnly ([be5167e](https://github.com/fergiemcdowall/search-index-adder/commit/be5167e))',
    meta:
     { 'x-ratelimit-limit': '5000',
       'x-ratelimit-remaining': '4997',
       'x-ratelimit-reset': '1499234292',
       'x-oauth-scopes': 'repo',
       location: 'https://api.github.com/repos/fergiemcdowall/search-index-adder/releases/6932093',
       etag: '"48c9e37b6d98af87149133b3ae640fe5"',
       status: '201 Created' } } ]

npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/fergusmcdowall/.nvm/versions/node/v7.9.0/bin/node" "/Users/fergusmcdowall/.nvm/versions/node/v7.9.0/bin/npm" "run" "github-release"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! search-index-adder@0.3.6 github-release: `conventional-github-releaser -p angular`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the search-index-adder@0.3.6 github-release script 'conventional-github-releaser -p angular'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the search-index-adder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     conventional-github-releaser -p angular
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs search-index-adder
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls search-index-adder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fergusmcdowall/.npm/_logs/2017-07-05T05_56_41_987Z-debug.log
```

**Comment by fergiemcdowall** [comment] 2017-07-06 14:42
@1.1.10 works fine- this problem appeared in @1.1.11

**Comment by hbetts** [comment] 2017-07-14 03:18
@fergiemcdowall, I looked through out changes between version `1.1.10` and `1.1.11`, of which there were three, and [all three](https://github.com/conventional-changelog/conventional-github-releaser/compare/01481d7e977d76d484ec95179dfaa849593616ed...9a18c37c5a35993c0669e535722692a88dcf451c) touch either our CI setup, or relax our Node requirements.

Can you please confirm you're using version 1.1.11 of `conventional-github-releaser`?

**Comment by zackarychapple** [comment] 2017-08-03 17:57
I got this error on 1.1.12.

**Comment by fergiemcdowall** [comment] 2017-08-03 19:42
Yes, actually it seems like the problem appeared in 1.1.12 for me too

**Comment by hbetts** [comment] 2017-08-04 03:37
Version 1.1.12 was released with the following commit (7c1e4d9) that introduced a fix to cause `conventional-github-releaser` to fail if, and only if, one or more POST requests to GitHub failed (400 or 500 errors).

I can't tell if that's actually what's happening based on the example output in the initial comment. I see a 201 response code, but my assumption is that `github.releases.createRelease` ([here](https://github.com/conventional-changelog/conventional-github-releaser/blob/master/src/index.js#L86) would be calling the callback function with `null` for the error since 201 is a valid success response. Therefore, we should be seeing a resolved promise, not a rejected promise followed by an error to console.

I'll put together a test case to walk through `conventional-github-releaser` and see how a 201 response is treated.

If y'all have a set of steps to quickly and easily reproduce this error, in addition to an example repository, it would really help me speed up the debugging process.

**Comment by danez** [comment] 2017-09-01 16:06
I have the same issue, it seems that this check is failing: https://github.com/conventional-changelog/conventional-github-releaser/blob/master/src/cli.js#L120-L129
The state property does not exist when using `Q.all` and only works with `Q.allSettled`.

I create a PR.

**Closed** 2017-10-30 16:44 UTC
Labels: support

**Comment by hbetts** [comment] 2017-10-30 17:28
Thanks to a bug fix submitted by @danez, version [v1.1.13](https://github.com/conventional-changelog/conventional-github-releaser/releases/tag/v1.1.13) has been released to address this issue.

**Comment by picosam** [comment] 2017-11-14 11:45
Hello, is this related?
→ conventional-github-releaser --version
2.0.0
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'github-release' ]
2 info using npm@5.5.1
3 info using node@v8.7.0
4 verbose run-script [ 'pregithub-release', 'github-release', 'postgithub-release' ]
5 info lifecycle hidsi-web@0.1.0~pregithub-release: hidsi-web@0.1.0
6 info lifecycle hidsi-web@0.1.0~github-release: hidsi-web@0.1.0
7 verbose lifecycle hidsi-web@0.1.0~github-release: unsafe-perm in lifecycle true
8 verbose lifecycle hidsi-web@0.1.0~github-release: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Sammy/Projects/hidsi-web/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle hidsi-web@0.1.0~github-release: CWD: /Users/Sammy/Projects/hidsi-web
10 silly lifecycle hidsi-web@0.1.0~github-release: Args: [ '-c', 'conventional-github-releaser -p angular' ]
11 silly lifecycle hidsi-web@0.1.0~github-release: Returned: code: 1  signal: null
12 info lifecycle hidsi-web@0.1.0~github-release: Failed to exec github-release script
13 verbose stack Error: hidsi-web@0.1.0 github-release: `conventional-github-releaser -p angular`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid hidsi-web@0.1.0
15 verbose cwd /Users/Sammy/Projects/hidsi-web
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/8.7.0/bin/node" "/usr/local/bin/npm" "run" "github-release"
18 verbose node v8.7.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error hidsi-web@0.1.0 github-release: `conventional-github-releaser -p angular`
22 error Exit status 1
```

**Comment by hbetts** [comment] 2017-11-14 16:35
@picosam I can't really tell from the output.

Can you please file a new issue, and let's work through debugging the issue?
